name: Builder Image

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/builder.yml'
      - 'builder.dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['25.05']
    steps:
      - 
        name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - 
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{vars.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - 
        name: Checkout
        uses: actions/checkout@v4
      - 
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          file: builder.dockerfile
          platforms: linux/amd64,linux/arm64
          tags: ${{vars.DOCKERHUB_USERNAME}}/tritonserverbuild:${{matrix.version}}-builder
          build-args: |
            NV_VERSION=${{matrix.version}}
